<a href="https://colab.research.google.com/github/YinGuoX/Deep_Learning_Pytorch_WithDeeplizard/blob/master/12_Tensors_For_Deep_Learning_Broadcasting_And_Element_Wise_Operations_With_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Element-Wise Tensor Operations For Deep Learning

 在这篇文章中，我们将通过学习元素操作来扩展我们的知识，而不仅仅是重塑操作。


## 1. 元素操作意味着？

在神经网络编程中，基于元素的操作是非常常见的带有张量的操作。 让我们以元素操作的定义开始讨论：

逐个元素的操作是两个张量之间的操作，该操作在各个张量内的相应元素上进行。

如果两个元素在张量中占据相同的位置，则称这两个元素是对应的。位置由用于定位每个元素的索引确定。

假设我们有以下两个张量：




In [ ]:
import torch
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

这两个张量均为2 x 2形状的rank-2张量。

这意味着我们有两个轴，每个轴的长度均为两个元素。 第一轴的元素是数组，第二轴的元素是数字。

In [ ]:
print(t1[0])

tensor([1., 2.])


In [ ]:
print(t1[0][0])

tensor(1.)


这是我们现在在本系列中经常看到的那种东西。 好吧，让我们以此为基础。

我们知道，如果两个元素在张量内处于相同位置，则认为这两个元素是对应的，并且该位置由用于定位每个元素的索引确定。 让我们看一个对应元素的例子。

In [ ]:
t1[0][0]

tensor(1.)

In [ ]:
t2[0][0]

tensor(9.)

这使我们看到t1中1的对应元素是t2中9的元素。

对应关系由索引定义。 这很重要，因为它揭示了元素方式操作的重要特征。 我们可以推断出张量必须具有相同数量的元素才能执行逐个元素的操作。

我们将继续进行此声明，使其更具限制性。 两个张量必须具有相同的形状，以便对其执行按元素的操作。

### 元素加法
  --- 
让我们看一下我们第一个基于元素的操作加法。 不用担心 它将变得更加有趣。


In [ ]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

这让我们看到张量之间的加法是一种元素操作。在相应位置的每一对元素被加在一起产生一个相同形状的新张量。

所以，加法是一种逐元素运算，实际上，所有的算术运算，加、减、乘、除都是逐元素运算。

## 2. 元素操作的算术运算
我们通常用张量看到的运算是使用标量值的算术运算。 我们可以通过两种方式执行此操作：

### 通过运算符进行算术运算

In [ ]:
print(t1)
print(t2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[9., 8.],
        [7., 6.]])


In [ ]:
print(t1+2)

tensor([[3., 4.],
        [5., 6.]])


In [ ]:
print(t1-2)

tensor([[-1.,  0.],
        [ 1.,  2.]])


In [ ]:
print(t1*2)

tensor([[2., 4.],
        [6., 8.]])


In [ ]:
print(t1/2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### 通过内置函数进行算术运算

In [ ]:
print(t1.add(2))

tensor([[3., 4.],
        [5., 6.]])


In [ ]:
print(t1.sub(2))

tensor([[-1.,  0.],
        [ 1.,  2.]])


In [ ]:
print(t1.mul(2))

tensor([[2., 4.],
        [6., 8.]])


In [ ]:
print(t1.div(2))

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


这两个选项的工作原理相同。 我们可以看到，在两种情况下，标量值2均通过相应的算术运算应用于每个元素。

这里似乎有些问题。 这些例子打破了我们建立的规则，即所述基于元素的运算在相同形状的张量上进行操作。

标量值是Rank-0张量，这意味着它们没有形状，而我们的张量t1是形状2 x 2的rank-2张量。

那么这如何适合呢？ 让我们分析一下。

可能想到的第一个解决方案是，该操作仅使用单个标量值并对张量内的每个元素进行操作。

这种逻辑的作品。 但是，这有点让人误解，并且在我们注意到使用标量的更一般的情况下，它会崩溃。

为了不同地考虑这些操作，我们需要引入张量广播或广播的概念。

### 广播张量
  ---
广播描述了不同形状的张量在元素操作中的处理方式。

广播是一个概念，它的实现允许我们向高维张量添加标量。

让我们考虑一下t1+2操作。这里，标量值张量被广播到t1的形状，然后，执行元素操作。

我们可以使用broadcast_to()函数查看广播标量值的外观：

In [ ]:
import numpy as np

np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

代码的意思是，将标量值像t1一样转换为rank-2张量，正好那样就形状匹配，并且具有相同形状的元素方式规则又重新发挥了作用。 当然，这全都在幕后。

也即是：

In [ ]:
t1+2

tensor([[3., 4.],
        [5., 6.]])

事实上就是：

In [ ]:
t1+torch.tensor(np.broadcast_to(2,t1.shape),dtype=torch.float32)

tensor([[3., 4.],
        [5., 6.]])

在这一点上，您可能会认为这似乎令人费解，所以让我们看一个更棘手的例子来说明这一点。 

### 一个更棘手的广播操作
假设我们有以下两个张量

In [ ]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

这个元素加法运算的结果是什么？对于元素操作，是否有可能给定相同的形状规则？

In [ ]:
t1.shape

torch.Size([2, 2])

In [ ]:
t2.shape

torch.Size([2])

尽管这两个张量有着不同的形状，但元素的操作是可能的，而广播则使操作成为可能。低秩张量t2将通过广播变换以匹配高秩张量t1的形状，并且将照常执行元素操作。

广播的概念是理解如何开展这项行动的关键。和前面一样，我们可以使用broadcast_to()函数检查广播转换。

In [ ]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [ ]:
t1+t2

tensor([[3., 5.],
        [3., 5.]])

广播后，这两个张量之间的加法运算是相同形状的张量之间的常规按元素运算。

[此文章](https://deeplizard.com/learn/video/6_33ulFDuCg)具有更详细的广播操作的讲解，请自行查阅。

## 2. 比较操作
比较操作也是按元素进行的操作。

对于两个张量之间的给定比较操作，将返回一个具有相同形状的新张量，其中每个元素都包含torch.bool值为True或False的元素。

PyTorch版本1.2.0中的行为更改

比较操作返回的数据类型已从更改为torch.uint8至torch.bool([21113](https://github.com/pytorch/pytorch/pull/21113)).



In [ ]:
torch.tensor([1,2,3])>torch.tensor([3,1,2])

tensor([False,  True,  True])

### 一些比较操作的例子



In [ ]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [ ]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [ ]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
t.gt(0)

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [ ]:
t.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
t.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

从广播的角度考虑这些操作，我们可以看到最后一个t.le（7）实际上是这样的：

In [ ]:
t <= torch.tensor(np.broadcast_to(7,t.shape),dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

等同于

In [ ]:
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)


## 3.一些元素操作的函数
使用作为函数的按元素操作，可以很好地假定该函数应用于张量的每个元素。

这里有些例子：

In [ ]:
t.abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [ ]:
t.sqrt()

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [ ]:
t.neg()

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [ ]:
t.neg().abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

一些术语

还有一些其他的方法来引用元素类型的操作，所以我只想提一下，所有这些操作的意思都是一样的:

* Element-wise
* Component-wise
* Point-wise