<a href="https://colab.research.google.com/github/YinGuoX/Deep_Learning_Pytorch_WithDeeplizard/blob/master/13_Code_For_Deep_Learning_ArgMax_And_Reduction_Tensor_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Reduction Ops For Deep Learning

## 1. Tensor Reduction Operations
让我们为Reduction操作的定义开始：
* 张量的Reduction操作是减少张量中包含的元素数量的运算。

到目前为止，在本系列文章中，我们已经了解到张量是深度学习的数据结构。 我们的首要任务是将数据元素加载到张量中。

因此，张量非常重要，但是最终，我们在本系列中已经学习的操作中正在做的事情是管理包含在我们的张量中的数据元素。

张量使我们能够管理数据。

Reshping操作使我们能够沿特定轴定位元素。 Element-wise运算允许我们对两个张量之间的元素执行运算，reduction运算允许我们对单个张量内的元素执行运算。

让我们来看一个代码示例。

In [ ]:
import torch

In [ ]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

让我们看一下我们的第一个归约运算：

In [ ]:
t.sum()

tensor(8.)

In [ ]:
t.numel()

9

In [ ]:
t.sum().numel()

1

In [ ]:
t.sum().numel() < t.numel()

True

我们使用sum（）张量方法计算张量的标量分量之和。这个调用的结果是一个标量值张量。

根据sum（）调用的结果检查原始张量中的元素数，我们可以看到，实际上，sum（）调用返回的张量包含的元素比原始张量少。

由于该操作减少了元素的数量，因此我们可以得出结论sum（）方法是一种Reduction操作。

### 常用的Tensor Reduction 操作
---

In [ ]:
t.sum()

tensor(8.)

In [ ]:
t.prod()

tensor(0.)

In [ ]:
t.mean()

tensor(0.8889)

In [ ]:
t.std()

tensor(1.1667)

所有这些张量方法通过对张量的所有元素进行运算，将张量化为一个单元素标量值张量。

缩减操作通常允许我们计算跨数据结构的聚合（总）值。在我们的例子中，我们的结构是张量。

但有一个问题：
* Reduction运算是否总是将一个张量归约为张量？

答案是不！

实际上，我们经常一次减少特定的轴。 这个过程很重要。 就像我们在重新调整批次中的图像张量同时仍保持批次轴的目的时看到的那样。

### Reducing Tensor的某个轴
--- 

为了减少相对于特定轴的张量，我们使用相同的方法，我们只是传递了维参数的值。 让我们看看实际情况。

假设我们有以下张量：

In [ ]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

这是一个3 x 4 rank-2张量。 两个轴的长度不同将有助于我们理解这些减少操作。

让我们再次考虑sum（）方法。 仅这次，我们将指定要减小的尺寸。 我们有两个轴，所以我们两个都做。 一探究竟。

In [ ]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [ ]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

当我第一次看到它的时候，我正在学习它是如何工作的，我很困惑。如果你和我一样困惑，我强烈建议你在继续之前先了解这里发生了什么。

记住，我们在第一个轴上减少张量，沿着第一个轴的元素是数组，沿着第二个轴的元素是数字。

我们来看看这里发生了什么。

我们将首先处理第一个轴。 当取第一轴的总和时，我们正在对第一轴的元素求和。

就像这样：

In [ ]:
t[0]

tensor([1., 1., 1., 1.])

In [ ]:
t[1]

tensor([2., 2., 2., 2.])

In [ ]:
t[2]

tensor([3., 3., 3., 3.])

In [ ]:
t[1]+t[2]+t[0]

tensor([6., 6., 6., 6.])

惊喜！元素操作在这里起作用。

当我们在第一个轴上求和时，我们取第一个轴上所有元素的和。要做到这一点，我们必须利用元素的加法。这就是为什么我们在这个系列的归约操作之前讨论了元素操作。

这个张量的第二个轴包含四个一组的数字。因为我们有三组四个数字，我们得到三个和。

In [ ]:
t[0].sum()

tensor(4.)

In [ ]:
t[1].sum()

tensor(8.)

In [ ]:
t[2].sum()

tensor(12.)

这可能需要花费一些时间。如果确实如此，请不用担心，您可以执行此操作。

现在，有了这繁重的工作。 现在让我们看一下在神经网络编程中使用的一种非常常见的归约运算，称为Argmax。

### Argmax Tensor Reduction Operation
--- 
Argmax是一个数学函数，它告诉我们当作为输入提供给函数时，哪个参数会导致函数的最大输出值。

Argmax返回张量中最大值的索引位置。

当我们对一个张量调用argmax（）方法时，这个张量被缩减为一个新的张量，其中包含一个索引值，指示最大值在张量中的位置。让我们看看这个代码。

假设我们有以下张量：

In [ ]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

在这个张量中，我们可以看到最大值是最后一个数组的最后一个位置的5。

假设我们是张量步行者。 要到达此元素，我们沿着第一个轴走直到到达最后一个数组元素，然后我们走到该数组的末尾并经过4和两个0。

让我们看一些代码。

In [ ]:
t.max()

tensor(5.)

In [ ]:
t.argmax()

tensor(11)

In [ ]:
t.flatten()

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

第一段代码为我们确认max确实为5，但是对argmax（）方法的调用告诉我们5位于索引11。这是怎么回事？

我们将看一下该张量的平展输出。 如果我们没有为argmax（）方法指定轴，它会从展平的张量中返回最大值的索引位置，在这种情况下，它的确为11。

让我们看看现在如何使用特定轴。

In [ ]:
t.max(dim=0)

torch.return_types.max(values=tensor([4., 3., 3., 5.]), indices=tensor([2, 1, 1, 2]))

In [ ]:
t.argmax(dim=0)

tensor([2, 1, 1, 2])

In [ ]:
t.max(dim=1)

torch.return_types.max(values=tensor([2., 3., 5.]), indices=tensor([3, 1, 3]))

In [ ]:
t.argmax(dim=1)

tensor([3, 1, 3])

在这段代码中，我们用的是张量的两个轴。注意对max（）方法的调用如何返回两个张量。第一个张量包含最大值，第二个张量包含最大值的索引位置。这就是argmax给我们的。

对于第一个轴，最大值为、4、3、3和5。这些值是通过在第一个轴上运行的每个数组上取元素最大值来确定的。

对于每个最大值，argmax（）方法告诉我们值所在的第一个轴上的哪个元素。

对于第二根轴，最大值为2、3和5。这些值是通过取第一根轴的每个数组内部的最大值来确定的。 我们有三组，每组四个，这给了我们3个最大值。

此处的argmax值告诉每个数组内的最大值所在的索引。

实际上，我们经常在网络的输出预测张量上使用argmax（）函数，以确定哪个类别具有最高的预测值。

## 2. Accessing Elements Inside Tensors

张量需要的最后一种常见操作是从张量内部访问数据的能力。 让我们来看看PyTorch的这些。

假设我们有以下张量：


In [ ]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [ ]:
t.mean()

tensor(5.)

In [ ]:
t.mean().item()

5.0

看看这个的操作。当我们在这个3x3张量上调用mean时，约化输出是一个标量值张量。如果我们真的想得到一个数值，我们可以使用item（）张量方法。这适用于标量值张量。

看看我们如何使用多个值：

In [ ]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]

In [ ]:
t.mean(dim=0).numpy()

array([4., 5., 6.], dtype=float32)

当我们计算第一个轴上的平均值时，将返回多个值，并且可以通过将输出张量转换为Python列表或NumPy数组来访问数值。

### 高级索引和切片
---
有了NumPy ndarray对象，我们有了一组非常健壮的索引和切片操作，而PyTorch张量对象也支持其中的大多数操作。

使用[此资源](https://numpy.org/doc/stable/reference/arrays.indexing.html)进行高级索引编制和切片。