<a href="https://colab.research.google.com/github/YinGuoX/Deep_Learning_Pytorch_WithDeeplizard/blob/master/29_Stack_Vs_Concat_In_PyTorch%2C_TensorFlow_%26_NumPy_Deep_Learning_Tensor_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Ops For Deep Learning: Concatenate Vs Stack
 在节中，我们将剖析concatenating和stacking张量之间的区别。 我们将看三个示例，一个示例使用PyTorch，一个使用TensorFlow，另一个使用NumPy。

## 1.现有轴与新轴
stacking张量和concatenating张量之间的差异可以用一个句子描述：
* Concatenating joins a sequence of tensors along an existing axis, and stacking joins a sequence of tensors along a new axis.

这就是全部！

这是stacking和concatenating之间的区别。 但是，这里的描述有些棘手，因此让我们看一些示例，以了解如何更好地理解这一点。 我们将研究PyTorch，TensorFlow和NumPy中的stacking和concatenating。 我们开始做吧。

在大多数情况下，沿着张量的现有轴进行contatenating非常简单。 当我们想沿着新的轴进行衔接时，通常会产生混乱。 为此，我们stacking。 表示stacking的另一种方式是，我们创建一个新轴，然后在该轴上合并。

|Join Method | Where|
| :---: | :---: |
|Concatenate|Along an existing axis|
|Stack|Along a new axis|

因此，请确保我们知道如何为给定张量创建新轴，然后开始stacking和concatenating。

### 如何在张量中添加或插入轴
---
为了演示添加轴的想法，我们将使用PyTorch。



In [ ]:
import torch
t1 = torch.tensor([1,1,1])
t1.shape

torch.Size([3])

在这里，我们要导入PyTorch并创建一个简单的张量，该张量具有一个长度为3的单轴。 现在，要在PyTorch中向张量添加轴，我们使用unsqueeze（）函数。 请注意，这与压缩相反。

In [ ]:
t1.unsqueeze(dim=0)


tensor([[1, 1, 1]])

In [ ]:
t1.unsqueeze(dim=0).shape

torch.Size([1, 3])

在这里，我们在这个张量的指数零点加一个轴，也就是维度。这给了我们一个形状为1x3的张量。当我们说张量的指数0时，我们指的是张量形状的第一个指数。

现在，我们还可以在该张量的第二个索引处添加一个轴。

In [ ]:
t1.unsqueeze(dim=1)


tensor([[1],
        [1],
        [1]])

In [ ]:
t1.unsqueeze(dim=1).shape

torch.Size([3, 1])

这给我们提供了一个3 x 1形状的张量。添加这样的轴会更改数据在张量内部的组织方式，但不会更改数据本身。 基本上，我们只是在重塑张量。 通过检查每个形状，我们可以看到这一点。

现在，回想一下concatenating和stacking的问题，当我们进行concatenating时，我们将沿着现有轴连接一系列张量。 这意味着我们正在扩展现有轴的长度。

当我们stacking时，我们正在创建一个以前不存在的新轴，并且这会在序列中的所有张量上发生，然后沿着这个新序列进行合并。

让我们看看如何在PyTorch中完成此操作。

## 2.在PyTorch中Stack Vs Cat

使用PyTorch，我们用于这些操作的两个函数是stack和cat。 让我们创建一个张量序列。

In [ ]:
import torch

t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

现在，让我们将它们彼此串联在一起。 请注意，每个张量都有一个轴。 这意味着cat函数的结果也将具有单个轴。 这是因为当我们连接时，我们会沿现有的轴进行连接。 请注意，在此示例中，唯一存在的轴是第一个轴。

In [ ]:
torch.cat((t1,t2,t3),dim=0)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

好了，所以我们取了三个单轴张量，每个轴张量的轴长为3，现在我们有了一个单张量，轴长为9。

现在，让我们沿着将要插入的新轴stacking这些张量。 我们将在第一个索引处插入一个轴。 请注意，此插入将通过stack()函数在后台隐式发生。

In [ ]:
torch.stack((t1,t2,t3),dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

这为我们提供了一个形状为3 x 3的新张量。请注意，这三个张量是如何沿着该张量的第一个轴连接的。 请注意，我们还可以显式插入新轴，并直接执行串联。

看看这个说法是对的。 让我们通过拉伸所有张量，向它们添加一个长度为1的新轴，然后沿着第一个轴concatenating。

In [ ]:
torch.cat((
    t1.unsqueeze(0),
    t2.unsqueeze(0),
    t3.unsqueeze(0),
),dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

在这个例子中，我们可以看到，我们得到的结果与stack得到的结果相同。但是，对stack的调用要干净得多，因为新的轴插入是由stack函数完成的。

* Concatenation happens along an existing axis.

请注意，由于当前不存在第二个轴，因此无法沿着第二个轴concatenaing此张量序列，因此在这种情况下，stacking是我们唯一的选择。

让我们尝试沿第二个轴stacking。

In [ ]:
torch.stack(
(t1,t2,t3),
dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

好的，我们相对于第二个轴叠加，这就是结果。

In [ ]:
torch.cat(
  (  t1.unsqueeze(1),
    t2.unsqueeze(1),
    t3.unsqueeze(1),)
  ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

要了解此结果，请回想一下在张量末端插入新轴时的外观。 现在，我们只需要对所有张量执行此操作，就可以沿着第二个轴对它们进行分类。 检查unsqueeze的输出可以帮助使这一点变得可靠。

In [ ]:
t1.unsqueeze(1)

tensor([[1],
        [1],
        [1]])

In [ ]:
t1.unsqueeze(1).shape

torch.Size([3, 1])

In [ ]:
t2.unsqueeze(1)

tensor([[2],
        [2],
        [2]])

In [ ]:
t3.unsqueeze(-1)

tensor([[3],
        [3],
        [3]])

## 3.TensorFlow中的Stack Vs Concat
现在让我们使用TensorFlow。

In [ ]:
import tensorflow as tf

t1 = tf.constant([1,1,1])
t2 = tf.constant([2,2,2])
t3 = tf.constant([3,3,3])

在这里，我们导入了TensorFlow并使用tf.constant（）函数创建了三个张量。 现在，让我们将这些张量彼此concatenate。 要在TensorFlow中执行此操作，我们使用tf.concat（）函数，而不是指定dim（如PyTorch），而是指定一个axis。 这两个意思相同。

In [ ]:
tf.concat((t1,t2,t3),axis=0)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int32)>

在这里，结果与我们使用PyTorch所做的结果相同。 好吧，让我们现在stack它们。

In [ ]:
tf.stack((t1,t2,t3),axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

同样，结果与PyTorch结果相同。 现在，我们将在手动插入新尺寸后将它们连接起来。

In [ ]:
tf.concat(
    (
        tf.expand_dims(t1,0)
        ,tf.expand_dims(t2,0)
        ,tf.expand_dims(t3,0)
    ),
    axis=0
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

与PyTorch调用相反，这个TensorFlow代码的区别在于cat（）函数现在被称为concat（）。此外，我们还使用expand_dims（）函数添加与unsqueze（）函数相对的轴。

* Unsqueezing and expanding dims mean the same thing.

好吧，让我们相对于第二个轴进行堆叠。

In [ ]:
tf.stack((t1,t2,t3),axis=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

并以手动轴的方式插入。

In [ ]:
tf.concat(
    (
        tf.expand_dims(t1,1),
        tf.expand_dims(t2,1),
        tf.expand_dims(t3,1)
    )
    ,axis=1
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

观察到这些结果与PyTorch一致。

## 4.NumPy中的Stack Vs Concatenate
现在让我们使用 NumPy。



In [ ]:
import numpy as np

t1 = np.array([1,1,1])
t2 = np.array([2,2,2])
t3 = np.array([3,3,3])
t1.shape

(3,)

在这里，我们创建了三个张量。 现在，让我们将它们彼此concatenate在一起。

In [ ]:
np.concatenate((t1,t2,t3),axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
np.concatenate((t1,t2,t3),axis=0).shape

(9,)

好吧，这给了我们我们所期望的。 请注意，与TensorFlow一样，NumPy也使用了轴参数名称，但是在这里，我们还看到了另一个命名变体。 NumPy使用完整单词串联作为函数名称。


|Library	|Function Name|
|:---:|:---:|
|PyTorch	|cat()|
|TensorFlow	|concat()|
|NumPy	|concatenate()|

好吧，让我们现在stack。

In [ ]:
np.stack((t1,t2,t3),axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

如预期的那样，结果是2级张量，其形状为3 x3。现在，我们将尝试手动方式。

In [ ]:
np.concatenate(
    (
        np.expand_dims(t1,0),
        np.expand_dims(t2,0),
        np.expand_dims(t3,0)
    ),
    axis=0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

请注意，结果与使用stack（）函数时的结果相同。 此外，请注意，NumPy还将术语expand dims用作函数名称。

现在，我们将使用第二个轴进行stack以完成此操作。

In [ ]:
np.stack((t1,t2,t3),axis=1)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

手动插入。

In [ ]:
np.concatenate(
    (
        np.expand_dims(t1,1),
        np.expand_dims(t2,1),
        np.expand_dims(t3,1)
    ),
    axis=1

)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## 5.Stack或Concat：真实示例
下面是我们在现实生活中可以遇到的三个具体例子。让我们决定什么时候需要stack，什么时候需要concatenate。

### 将图像合并为一个批处理
---
假设我们有三个单独的图像作为张量。 每个图像张量具有三个维度，即通道轴，高度轴，宽度轴。 请注意，每个张量彼此独立。 现在，假设我们的任务是将这些张量连接在一起以形成三个图像的单批张量。

* 我们是concat还是stack？

好吧，请注意，在此示例中，仅存在三个维度，而对于一个批次，我们需要四个维度。 这意味着答案是沿着新轴stack张量。 该新轴将成为批处理轴。 通过为批次添加一个张量，这将为我们提供具有四个尺寸的单个张量。

请注意，如果我们沿任何现有尺寸将这三个尺寸结合在一起，则会弄乱通道，高度或宽度。 我们不想这样弄乱我们的数据。

In [ ]:
import torch
t1 = torch.zeros(3,28,28)
t2 = torch.zeros(3,28,28)
t3 = torch.zeros(3,28,28)


In [ ]:
torch.stack(
    (t1,t2,t3),
    dim=0
).shape

torch.Size([3, 3, 28, 28])

### 将多个批次合并为一个批次
---
现在，假设我们具有与以前相同的三个图像，但是这次图像已经具有该批次的尺寸。 这实际上意味着我们有三批尺寸为1的批次。 假设获得单批三个图像是我们的任务。

* 我们是合并还是堆叠？

好吧，请注意如何可以存在一个现有维度。 这意味着我们在批处理维度上将它们合并在一起。 在这种情况下，无需堆叠。

这是一个代码示例：


In [ ]:
import torch
t1 = torch.zeros(1,3,28,28)
t2 = torch.zeros(1,3,28,28)
t3 = torch.zeros(1,3,28,28)

In [ ]:
torch.cat(
    (t1,t2,t3),
    dim=0
).shape

torch.Size([3, 3, 28, 28])

让我们看看第三个。 这个很难。 或至少更高级。 您会明白为什么

### 结合现有批次的图​​像
---
假设我们有相同的三个单独的图像张量。 只是这次，我们已经有了一个批处理张量。 假设我们的任务是将这三个单独的图像与批次结合在一起。

* 我们是合并还是堆叠？

好吧，请注意批处理轴中的批处理轴已经存在。 但是，对于图像，不存在批处理轴。 这意味着这些都不起作用。 要与stack或cat连接，我们需要张量具有匹配的形状。 那么，我们被卡住了吗？ 这不可能吗？

确实有可能。 这实际上是非常常见的任务。 答案是先堆叠然后再连接。

我们首先堆叠相对于第一维的三个图像张量。 这将创建一个长度为3的新批次尺寸。 然后，我们可以用批处理张量连接这个新的张量。

让我们在代码中看一个例子：




In [ ]:
import torch
batch = torch.zeros(3,3,28,28)
t1 = torch.zeros(3,28,28)
t2 = torch.zeros(3,28,28)
t3 = torch.zeros(3,28,28)

In [ ]:
torch.cat(
    (
        batch,
        torch.stack(
            (t1,t2,t3),
            dim=0
        )
    ),
    dim=0
).shape

torch.Size([6, 3, 28, 28])

同样地：

In [ ]:
import torch
batch = torch.zeros(3,3,28,28)
t1 = torch.zeros(3,28,28)
t2 = torch.zeros(3,28,28)
t3 = torch.zeros(3,28,28)

In [ ]:
torch.cat(
    (
        batch,
        t1.unsqueeze(0),
        t2.unsqueeze(0),
        t3.unsqueeze(0)
    ),
    dim=0
).shape

torch.Size([6, 3, 28, 28])

我希望这会有所帮助，并且您现在就掌握了。