<a href="https://colab.research.google.com/github/YinGuoX/Deep_Learning_Pytorch_WithDeeplizard/blob/master/8_PyTorch_Tensors_Explained_Neural_Network_Programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducing PyTorch Tensors
PyTorch张量是在的中编程神经网络时所使用的数据结构。

在神经网络编程时，数据预处理往往是整个过程中的第一步，数据预处理的目标之一就是将原始输入数据转化为张量形式。

## 1. torch.Tensor类的实例
PyTorch张量是torch.Tensor Python类的实例。 我们可以使用类构造函数创建torch.Tensor对象，如下所示：

In [ ]:
import torch

In [ ]:
t = torch.Tensor()
type(t)

torch.Tensor

这将创建一个空的张量（没有数据的张量），但是我们将在片刻内添加数据。

## 2.Tensor的属性
首先，让我们看一些张量属性。 每个torch.Tensor具有以下属性：
* torch.dtype
* torch.device
* torch.layout


In [ ]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


torch.dtype的各种类型：

注意每种类型都有一个CPU和GPU版本。关于张量数据类型，需要记住的一点是，张量之间的张量操作必须发生在具有相同数据类型的张量之间。但是，此语句仅适用于低于1.3的PyTorch版本。详细信息请参见下面关于PyTorch张量类型提升的部分。


| Data type | dtype | CPU tensor | GPU tensor |
| :-----: | :----: | :----: | :----: |
| 32-bit floating point | torch.float32 | torch.FloatTensor | torch.cuda.FloatTensor|
| 64-bit floating point | torch.float64 | torch.DoubleTensor | torch.cuda.DoubleTensor|
| 16-bit floating point | torch.float16 | torch.HalfTensor | torch.cuda.HalfTensor|
| 8-bit integer(unsigned) | torch.uint8 | torch.ByteTensor | torch.cuda.ByteTensor|
| 8-bit integer(signed) | torch.int8 | torch.CharTensor | torch.cuda.CharTensor|
| 16-bit integer(signed) | torch.int16 | torch.ShortTensor | torch.cuda.ShortTensor|
| 32-bit integer(signed) | torch.int32 | torch.IntTensor | torch.cuda.IntTensor|
| 64-bit integer(signed) | torch.int64 | torch.LongTensor | torch.cuda.LongTensor|




Pytorch Tensor的类型提升

从PyTorch 1.3版开始，算术和比较运算可以执行提升为普通dtype的混合类型运算。

以下示例在1.2版中是不允许的。 但是，在1.3版及更高版本中，相同的代码将返回带有dtype = torch.float32的张量。

In [ ]:
torch.tensor([1],dtype=torch.int)+torch.tensor([1],dtype=torch.float32)

tensor([2.])

有关更多详细信息，请参见完整的[文档](https://github.com/pytorch/pytorch/blob/master/docs/source/tensor_attributes.rst#type-promotion-doc):
* torch.result_type Provide function to determine result of mixed-type ops [26012](https://github.com/pytorch/pytorch/pull/26012).
* torch.can_cast Expose casting rules for type promotion [26805](https://github.com/pytorch/pytorch/pull/26805).
* torch.promote_types Expose promotion logic [26655](https://github.com/pytorch/pytorch/pull/26655).

In [ ]:
torch.result_type

<function _VariableFunctionsClass.result_type>

torch.device的使用：

在我们的例子中，设备 CPU 指定了分配张量数据的设备(CPU 或 GPU)。这决定了给定张量的张量计算将在哪里进行。

支持使用多个设备，并且使用如下索引指定它们

In [ ]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

如果我们有一个像上面这样的设备，我们可以通过将设备传递给张量的构造函数在设备上创建一个张量。使用多个设备需要记住的一点是，张量之间的张量操作必须发生在同一设备上的张量之间。

当我们成为更高级的用户时，使用多个设备通常是我们要做的事情，所以现在不必担心这一点。

torch.layout的使用

在我们的例子中，这种布局指定了张量如何存储在内存中。想了解更多关于步幅的信息，请点击[这里](https://en.wikipedia.org/wiki/Stride_of_an_array)。

目前，我们只需要知道这些。

作为神经网络程序员，我们需要注意以下几点:

张量包含统一类型(dtype)的数据。

张量之间的张量计算取决于dtype和device。

现在让我们来看一下使用 PyTorch 中的数据创建张量的常用方法。


## 3.创建Tensor
以下是使用 PyTorch 中的数据(类似数组)创建张量对象(torch. Tensor 类的实例)的主要方法:

* torch.Tensor(data)
* torch.tensor(data)
* torch.as_tensor(data)
* torch.from_numpy(data)

让我们来看看这些。他们都接受某种形式的数据，并给我们一个torch.Tensor实例类。有时候，当有多种方法可以达到同样的结果时，事情可能会变得混乱，所以让我们来分析一下。

我们将首先对每个选项创建一个张量，然后看看我们得到了什么。我们将从创建一些数据开始。

我们可以使用 Python list 或者 sequence，但是 numpy.ndarray 将是更常见的选项，所以我们将使用 numpy.ndarray，如下所示:

In [ ]:
import numpy as np

data = np.array([1,2,3])
type(data)

numpy.ndarray

这为我们提供了一个简单的数据位类型numpy.ndarray公司.

现在，让我们用上面这些选项中的每一个来创建我们的张量，看看我们得到了什么：

In [ ]:
o1= torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)
o4 = torch.from_numpy(data)

In [ ]:
print(o1,o1.dtype)
print(o2,o2.dtype)
print(o3,o3.dtype)
print(o4,o4.dtype)

tensor([1., 2., 3.]) torch.float32
tensor([1, 2, 3]) torch.int64
tensor([1, 2, 3]) torch.int64
tensor([1, 2, 3]) torch.int64


所有的选项（o1，o2，o3，o4）似乎都产生了相同的张量，除了第一个。第一个选项（o1）在数字后面有点，表示数字是浮点数，而后面三个选项的类型是int64。

In [ ]:
type(2.)

float

In [ ]:
type(2)

int

在下节中，我们将更深入地研究这种差异，以及潜伏在幕后的其他一些重要差异。

下节文章中的讨论将让我们看到这些选项中哪一个最适合创建张量。现在，让我们看看一些创建选项，这些选项可用于在没有预先任何数据的情况下从头创建张量。

## 4.无数据创建Tensor
这里有一些其他可用的创建选项。
* torch.eye()
* torch.zeros()
* torch.ones()
* torch.rand()

我们有torch.eye ()函数，它返回一个2-D 张量，其中1在对角线上，0在其他地方。名称 eye ()与单位矩阵的思想相关，单位矩阵是一个在主对角线上有1的方阵，其他地方都是零。


In [ ]:
print(torch.eye(2))

tensor([[1., 0.],
        [0., 1.]])


我们有torch.zero（）函数，用于创建具有指定形状参数形状的零张量

In [ ]:
print(torch.zeros([2,2]))

tensor([[0., 0.],
        [0., 0.]])


类似地，我们有 torch.ones ()函数，它创建一个全部为
1的张量。

In [ ]:
print(torch.ones([2,2]))

tensor([[1., 1.],
        [1., 1.]])


我们还有一个 torch.rand ()函数，它创建一个具有指定参数形状的张量，其值是随机的。

In [ ]:
print(torch.rand([2,2]))

tensor([[0.6595, 0.4499],
        [0.1020, 0.3773]])


这是不需要数据的可用创建函数的一小部分。查看[PyTorch文档](https://pytorch.org/docs/stable/index.html)以获取完整的说明。

我希望现在您已经很好地理解了如何使用PyTorch通过使用数据以及不需要数据的内置函数来创建张量。

在下一篇文章中，我们将更深入地研究需要数据的创建选项，我们将发现这些选项之间的差异，并查看哪些选项最有效。下次见！